[package]
name = "rusty2"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-rt = '1.0.0'
actix-web = '2.0'
serde = {version = '1.0.104', features = ["derive"]}
dotenv = "0.15.0"
config = "0.10.1"

# cargo watch -q -c -x run

