
### All Lists
GET http://localhost:8080/all-lists



### One List
GET http://localhost:8080/one-list/?id=1



### Create List
POST http://localhost:8080/create_list
Content-Type: application/json

{
  "title": "List4"
}


### Create Item
POST http://localhost:8080/create_item
Content-Type: application/json

{
  "title": "Item6",
  "list_id": 1
}


### Checked Item
PATCH http://localhost:8080/checked_item/?id=92